version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - ${DATABASE_POSTGRES_PORT}:${DATABASE_POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${DATABASE_POSTGRES_DB}
      POSTGRES_USER: ${DATABASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_PASSWORD}
